# -*- coding: utf-8 -*-

# TSK_FS_TYPE

TSK_FS_TYPE_NTFS = 1
TSK_FS_TYPE_NTFS_DETECT = 1

# TSK_FS_ATTR_TYPES
TSK_FS_ATTR_TYPE_NOT_FOUND = 0
TSK_FS_ATTR_TYPE_DEFAULT = 1
TSK_FS_ATTR_TYPE_NTFS_ATTRLIST = 32
TSK_FS_ATTR_TYPE_NTFS_BITMAP = 176
TSK_FS_ATTR_TYPE_NTFS_DATA = 128
TSK_FS_ATTR_TYPE_NTFS_EA = 224
TSK_FS_ATTR_TYPE_NTFS_EAINFO = 208
TSK_FS_ATTR_TYPE_NTFS_FNAME = 48
TSK_FS_ATTR_TYPE_NTFS_IDXALLOC = 160
TSK_FS_ATTR_TYPE_NTFS_IDXROOT = 144
TSK_FS_ATTR_TYPE_NTFS_LOG = 256
TSK_FS_ATTR_TYPE_NTFS_OBJID = 64
TSK_FS_ATTR_TYPE_NTFS_PROP = 240
TSK_FS_ATTR_TYPE_NTFS_REPARSE = 192
TSK_FS_ATTR_TYPE_NTFS_SEC = 80
TSK_FS_ATTR_TYPE_NTFS_SI = 16
TSK_FS_ATTR_TYPE_NTFS_SYMLNK = 192
TSK_FS_ATTR_TYPE_NTFS_VINFO = 112
TSK_FS_ATTR_TYPE_NTFS_VNAME = 96
TSK_FS_ATTR_TYPE_NTFS_VVER = 64
TSK_FS_ATTR_TYPE_HFS_DEFAULT = 1

ATTRIBUTE_TYPES_TO_ANALYZE = [
    TSK_FS_ATTR_TYPE_NTFS_IDXROOT,
    TSK_FS_ATTR_TYPE_NTFS_DATA,
    TSK_FS_ATTR_TYPE_NTFS_FNAME,
    TSK_FS_ATTR_TYPE_NTFS_SI,
    TSK_FS_ATTR_TYPE_DEFAULT,
    TSK_FS_ATTR_TYPE_HFS_DEFAULT
]

ATTRIBUTE_TYPES_TO_ANALYZE_TIME = [
    TSK_FS_ATTR_TYPE_NTFS_SI,
    TSK_FS_ATTR_TYPE_HFS_DEFAULT
]
ATTRIBUTE_TYPES_TO_ANALYZE_ADDITIONAL_TIME = [
    TSK_FS_ATTR_TYPE_NTFS_FNAME
]
'''
# TSK_FS_NAME_TYPE
TSK_FS_NAME_TYPE_UNDEF = 0
TSK_FS_NAME_TYPE_FIFO = 1
TSK_FS_NAME_TYPE_CHR = 2
TSK_FS_NAME_TYPE_DIR = 3
TSK_FS_NAME_TYPE_BLK = 4
TSK_FS_NAME_TYPE_REG = 5
TSK_FS_NAME_TYPE_LNK = 6
TSK_FS_NAME_TYPE_SOCK = 7
TSK_FS_NAME_TYPE_SHAD = 8
TSK_FS_NAME_TYPE_WHT = 9
TSK_FS_NAME_TYPE_VIRT = 10
TSK_FS_NAME_TYPE_VIRT_DIR = 11

FILE_TYPE_LOOKUP = {
    TSK_FS_NAME_TYPE_UNDEF: "-",    # Unknown type
    TSK_FS_NAME_TYPE_FIFO: "p",     # Named pipe NON-NLS
    TSK_FS_NAME_TYPE_CHR: "c",      # Character device NON-NLS
    TSK_FS_NAME_TYPE_DIR: "d",      # Directory NON-NLS
    TSK_FS_NAME_TYPE_BLK: "b",      # Block device NON-NLS
    TSK_FS_NAME_TYPE_REG: "r",      # Regular file NON-NLS
    TSK_FS_NAME_TYPE_LNK: "l",      # Symbolic link NON-NLS
    TSK_FS_NAME_TYPE_SOCK: "h",     # Socket NON-NLS
    TSK_FS_NAME_TYPE_SHAD: "s",     # Shadow inode (solaris) NON-NLS
    TSK_FS_NAME_TYPE_WHT: "w",      # Whiteout (openbsd) NON-NLS
    TSK_FS_NAME_TYPE_VIRT: "v",     # Special (TSK added "Virtual" files) NON-NLS
    TSK_FS_NAME_TYPE_VIRT_DIR: "V"  # Special (TSK added "Virtual" directories) NON-NLS
}

# TSK_FS_META_TYPE
TSK_FS_META_TYPE_UNDEF = 0
TSK_FS_META_TYPE_REG = 1
TSK_FS_META_TYPE_DIR = 2
TSK_FS_META_TYPE_FIFO = 3
TSK_FS_META_TYPE_CHR = 4
TSK_FS_META_TYPE_BLK = 5
TSK_FS_META_TYPE_LNK = 6
TSK_FS_META_TYPE_SHAD = 7
TSK_FS_META_TYPE_SOCK = 8
TSK_FS_META_TYPE_WHT = 9
TSK_FS_META_TYPE_VIRT = 10
TSK_FS_META_TYPE_VIRT_DIR = 11

META_TYPE_LOOKUP = {
    TSK_FS_META_TYPE_UNDEF: "-",    # Unknown type
    TSK_FS_META_TYPE_REG: "r",      # Regular file NON-NLS
    TSK_FS_META_TYPE_DIR: "d",      # Directory file NON-NLS
    TSK_FS_META_TYPE_FIFO: "p",     # Named pipe (fifo) NON-NLS
    TSK_FS_META_TYPE_CHR: "c",      # Character device NON-NLS
    TSK_FS_META_TYPE_BLK: "b",      # Block device NON-NLS
    TSK_FS_META_TYPE_LNK: "l",      # Symbolic link NON-NLS
    TSK_FS_META_TYPE_SHAD: "s",     # SOLARIS ONLY NON-NLS
    TSK_FS_META_TYPE_SOCK: "h",     # UNIX domain socket NON-NLS
    TSK_FS_META_TYPE_WHT: "w",      # Whiteout NON-NLS
    TSK_FS_META_TYPE_VIRT: "v",     # "Virtual File" created by TSK for file system areas NON-NLS
    TSK_FS_META_TYPE_VIRT_DIR: "v"  # "Virtual Directory" created by TSK for Orphan Files NON-NLS
}
'''


OPERATING_SYSTEM_FAMILY_LINUX = 'Linux'
OPERATING_SYSTEM_FAMILY_MACOS = 'MacOS'
OPERATING_SYSTEM_FAMILY_UNKNOWN = 'Unknown'
OPERATING_SYSTEM_FAMILY_WINDOWS_9x = 'Windows 9x/Me'
OPERATING_SYSTEM_FAMILY_WINDOWS_NT = 'Windows NT'

OPERATING_SYSTEM_FAMILIES = frozenset([
    OPERATING_SYSTEM_FAMILY_LINUX,
    OPERATING_SYSTEM_FAMILY_MACOS,
    OPERATING_SYSTEM_FAMILY_UNKNOWN,
    OPERATING_SYSTEM_FAMILY_WINDOWS_9x,
    OPERATING_SYSTEM_FAMILY_WINDOWS_NT])

PROCESS_STATE_COMPLETE = 0
PROCESS_STATE_PROCESSING = 1
PROCESS_STATE_READY = 2